title:        Andrew G Johnson.com
name:         Andrew G Johnson.com
description:  Andrew G Johnson is a software engineer, web developer and technologist from Winnipeg, Manitoba, Canada
author:       Andrew G Johnson
author_email: andrew@andrewgjohnson.com
email:        andrew@andrewgjohnson.com
url:          "https://www.andrewgjohnson.com"
includes_dir: .
layouts_dir:  _layouts
exclude:      [
               .github,
               .github/*.md,
               .github/*.yml,
               .github/CODEOWNERS,
               CNAME,
               gulpfile.js,
               layouts,
               layouts/*,
               node_modules,
               node_modules/*,
               package.json,
               package-lock.json,
               README.md
              ]
